name: Run R Script

on:
  workflow_dispatch: # Allows manual trigger too
  schedule:
    - cron: '0 10 * * *' # Every day at 10 AM UTC (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: '4.3.2'
          
    - name: Cache R packages
      uses: actions/cache@v4
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libicu-dev \
          libfreetype6-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libpng-dev \
          libfontconfig1-dev \
          libtiff5-dev \
          libjpeg-dev \
          libglpk-dev \
          libcairo2-dev \
          libxt-dev \
          libzstd-dev

    - name: Install required R packages
      run: |
        Rscript -e '.libPaths("~/.local/share/renv"); packages <- c(
          "tidyverse", "conflicted", "lubridate", "skimr", "janitor",
          "purrr", "fs", "stringi", "fuzzyjoin", "scales", "curl", "cansim"
        ); install.packages(setdiff(packages, rownames(installed.packages())))'

    - name: Run R script
      run: Rscript load.R

    - name: Upload result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: contracts_analysis_results
        path: data/out/
