name: Run R Script

on:
  workflow_dispatch: # Allows manual trigger too
  schedule:
    - cron: '0 10 * * *' # Every day at 10 AM UTC (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: '4.2.2'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libicu-dev \
          libfreetype6-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libpng-dev \
          libfontconfig1-dev \
          libtiff5-dev \
          libjpeg-dev \
          libglpk-dev \
          libcairo2-dev \
          libxt-dev \
          libzstd-dev

    - name: Install required R packages
      run: |
        Rscript -e 'install.packages(c(
          "tidyverse", "conflicted", "lubridate", "skimr", "janitor",
          "purrr", "fs", "stringi", "fuzzyjoin", "scales", "curl"
        ))'

    - name: Run R script
      run: Rscript load.R

    - name: Upload result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: contracts_output
        path: data/out/contract_spending_overall_expiring_2025.csv
