name: Run R Script

on:
  workflow_dispatch: # Allows manual trigger too
  schedule:
    - cron: '0 10 * * *' # Every day at 10 AM UTC (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: '4.2.2'

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("dplyr", "tidyr", "readr", "stringr", "jsonlite", "httr", "lubridate", "purrr"))'

    - name: Run R script
      run: Rscript load.R

    - name: Upload result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: contracts_output
        path: data/out/contract_spending_overall_expiring_2025.csv
